### ISSUE TITLE
** Preparation for Release 3.3.0 **

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1109]
This issue is created to collect all the tasks we need to do before the 3.3.0

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#1107)
- [x] Update Readme.md (#1107)
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### Refactoring 
- [x] Support for SSL session resumption in TcpConnection and TcpServer. (#1110)
- [x] Http Client and Http Server. (#1112)

### Changes
- [ ] Adding support for SDK 2.1.0 (#1153) 
- [x] Station::waitConnection (also WifiStation::waitConnection was deprecated and is now removed. (#1171)
- [x] Custom PWM is enabled by default. (#1164)
- [x] Multiple fixes to issues reported from Codacy's Vera++ and CppCheck reports.

**Comment by kwis2** [comment]
I found `chocolately` problem was lost between 3.2.0 and 3.3.0 versions

**Comment by slaff** [comment]
> I found chocolately problem was lost between 3.2.0 and 3.3.0 versions

We don't have the people that can solve it for now. Anyone who is working on Windows is welcome to help us.

**Comment by Vity01** [comment]
Maybe I should define new issue for this, but current latest develope branch is not compilable on Windows. 
I tried to do that without Chocolately. Eg. the makefile in SmingFramework contains '$(shell find SmingCore -type d)' which calls unix command. I replaced that with concrete folders, after more tuning folder settings I was able to compile without error.
Next I tried to build sample HttpClient_Teamspeak with an error 'collect2.exe: error: ld returned 1 exit status'. Wiki describes this error as a problem with a framework compilation...

**Comment by icodk** [comment]
@Vity01 
Thanks for mention it. There are few  previous issues (1140 and 1149)  that unfortunately  never addressed by any of the experts on  this repository. Looks like Sming's  Windows  comparability is  silently deprecated.
It is not a complain it is an observation. The probable cause is shortage of experts time.

**Comment by Vity01** [comment]
Is 3.3 already compatible with Windows?

**Comment by slaff** [comment]
@Vity01 It should be. If you are using choco something like this should download for you the latest version
```
choco upgrade -y -f sming.core --version 0.0.4
```
