### ISSUE TITLE
*** Preparation for Release 3.4.0 ***

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1195]
This issue is created to collect all the tasks we need to do before the 3.4.0.
This release will be targeting better Arduino compatibility.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h
- [x] Update Readme.md
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### Refactoring 
- [x] Fix the Wire param order to match Arduino (#1193)
- [x] Add pgmspace.h (#1213)
- [x] Use the ESP8266 directive and adjust the code respectively (#1192)
- [x] Fix wrong GPIO reg type ( #1213 )
- [x] Improve HttpClient and HttpServer handling of "large" or "endless" streams. (#1247)
- [x] Make setting body parsers in the HttpServer to allow wildcards (#1254).

And implementing ideas from #1035.

**Comment by Vity01** [comment]
@slaff The last check on refactoring topic can be marked as done - see https://github.com/SmingHub/Sming/pull/398

**Comment by kwis2** [comment]
According to #1230 and #1239 it would be good idea to be able to disable stack dump in next release

**Comment by slaff** [comment]
@kwis2 That is already possible. When you compile Sming and the application using Sming make sure to add the SMING_RELEASE=1 directive. For example:

```
cd $SMING_HOME
make dist-clean
make SMING_RELEASE=1
```

will compile library for you without debug statements and stack dumps.

See: https://github.com/SmingHub/Sming/blob/develop/Sming/Makefile#L185
