### ISSUE TITLE
Preparation for Release 3.5.0.

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1278]
This issue is created to collect all the tasks we need to do before the 3.5.0.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#1295)
- [x] Update Readme.md (#1295)
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### New Features and Improvements
- [x] Updated the Readme and added documentation explaining how to enable LWIP2 or/and SDK 2.1 **experimental** features (#1295)
- [x] Better rBoot and spiffs support (#1292) 
- [x] Added method to shutdown a TcpServer (#1272).
- [x] Added Adafruit_BME280 Library (#1286).
- [x] Improve websocket ping and pong commands (#1270).
- [x] Added **experimental** support for SDK 2.1 (#1264).
- [x] Added **experimental** support for LWIP2 (#1289) 

All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/13)
