### ISSUE TITLE
*** Preparation for Release 3.5.1 ***

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1296]
This issue is created to collect all the tasks we need to do before the 3.5.1.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#1334)
- [x] Update Readme.md (#1334)
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### New Features and Improvements
- [x] Unified the stream classes for better testability and reusability. (#1332) The `length()` method in the DataSourceStream classes is deprecated and will be removed in the coming versions. Use `available()` instead.
- [x] MacOS compatibility issues. (#1316)
- [x] Memory Optimization: Moved C++ vtables into IRAM, out of HEAP. In some cases increased the free heap with 3K. (#1320)
- [x] Updated axTLS to its latest version and increased available free heap (#1329).
- [x] Decreased the default debug messages in the network layer (#1327) as part of our effort to provide better out-of-the-box experience (#1328)
- [x] Reorganization: Moved the tools under tools/ folder and added esptool2 as submodule as part of the better experience.
- [x]  Fix: Added linker flags to allow the use of custom crash handlers in the user code. (#1326)
- [x] Small fix to the FreeBSD make mechanism.
- [x] HardwareSerial: Fix for zero availableCharsCount in callback ... (#1307)
- [x] Adds Cygwin32 build support (#1306)
- [x] Modified libemqtt & MqttClient to allow the publishing of binary messages (#1300)

All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/14)
