### ISSUE TITLE
*** Preparation for Release 3.5.2 ***

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1340]
This issue is created to collect all the tasks we need to do before the 3.5.2.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#1369 ) 
- [x] Update Readme.md ( #1369 )
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### New Features and Improvements
All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/15)

- [x] The C++ part should use std::max and std::min instead of the max. PR #1368.
- [x] Updated PWM to its latest version. PR #1360.
- [x] Prevent "already-freed" error from happening. PR #1359, #1342.
- [x] Updated the Http parser to its latest version. PR #1350.
- [x] Fixed reading of http body from stream PR #1349.
- [x] Better support for libraries that rely on Adafruit_Sensor.  PR #1344.

**Comment by kwis2** [comment]
Maybe it will be possible to add ability to work with windows ??? #1297, #1241

**Comment by frankdownunder** [comment]
Any chance of getting SMTP Sample #1312 into this release?

**Comment by slaff** [comment]
The SmtpClient in its current state is not ready for a release. Some days ago I started to write a text with the issues that are there nd how to program in async manner and suddenly ended up with a version that, hopefully soon, will be a full-featured performant SMTP client for embedded devices. 
You can follow the progress from here: https://github.com/slaff/Sming/tree/feature/smtp-client  and that client will replace your PR.

**Comment by frankdownunder** [comment]
Excellent.   I will study your code, hopefully will learn some tricks.

Sent from Mail for Windows 10

**Comment by kwis2** [comment]
According to #1354 in my opinion it is high time to say that Sming is not supported on Windows

**Comment by slaff** [comment]
v3.5.2 is officially released: https://github.com/SmingHub/Sming/releases/tag/3.5.2.
