### ISSUE TITLE
Preparation for Release 3.6.0

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1371]
This issue is created to collect all the tasks we need to do before the 3.6.0.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h #1404
- [x] Update Readme.md #1404
- [x] Merge develop into master
- [x] Tag the source code in the master branch

## Financial contributions
Since this version we added support for OpenCollective. 
- [x] Replaced the Donate button with something more transparent - how much money are donated per 
month, etc. With those money we can run hackathons and speed up the development. #1398

### New Features and Improvements
- [x] Improvements to the InfraRed libraries #1318 
- [x] Usage of C++11 `std::function` in Timer #1378
- [x] Refactoring of the data streams and HttpClient and HttpServer #1377 
- [x] Support for POST params and file uploads in the HttpClient #1381
- [x] SmtpClient. #1380 
- [x] HttpClient: Don't read the complete response body. Limit it to 1024 bytes by default #1386
- [x] Added support for Nextion displays. #1389
- [x] Replaced DHT library with DHTesp. Updated the samples accordingly. #1341
- [x] Bug fixes related to unescaping of post params . #1402
- [x] MqttClient: allows changing server and port setting in runtime (#1390)

### Documentation
- Updates to the Readme file #1385

- [x] Once ready with the changes above ask @riban-bw to proof-read the Readme. At the moment it has multiple typos like "Put you SSID and Password here" that should be "Put you**r** SSID and Password here" #1403
- [x] remove esptool2 from "Additional needed software". In the latest versions it is coming with the framework.
- [x] Update the DHT22 example. Add link to the sample code.
- [x] For the HttpServer  - add link to the samples related to it.
- [x] Serial communication - add link to the samples related to it.
- [x] Documentation - put link to the available online documentation.
- [x] OTA application update based on rBoot -   add link to the Basic_rBoot sample.
- [x] Remove `esp-alt-sdk` from the list of supported SDKs.
- [x] "Simple GPIO input/output" - add link to the Basic_Blink sample.

All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/16)

**Comment by riban-bw** [comment]
Need to change erroneous reference to 3.5.2 in first sentence. (Three me for a moment!)
