### ISSUE TITLE
Preparation for Release 3.6.1

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#1399]
This issue is created to collect all the tasks we need to do before the 3.6.1.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h #1424 
- [x] Update Readme.md #1424 
- [x] Merge develop into master
- [x] Tag the source code in the master branch

# Coding Style Rules
- [ ] Update the README and Contributions to have section about coding standards.
- [x] Make a separate PR that should be squashed and merged as a single commit that has all coding style fixes already applied. #1400
- [x] Add git file attributes file that takes care for preserving the line endings without the need for additional command line parameters. #1421
- [x] Create a [document](https://github.com/SmingHub/Sming/wiki/Coding-Style-Rules) that helps developers apply the coding style rules before submitting a PR.
- [x] add .clang_format file with the described coding style. #1400 
- [x] Create a list of directories where the coding style should be applied (Sming/SmingCore and samples ). Exclude external code like Arduino libraries or third_party code. 
- [x] update the travis build script to check new PRs for coding style issues and report them.  #1400 

# Automation
- [x] Update the chocolate packages on new release. (#1406)

All PRs scheduled for this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/17)
