### ISSUE TITLE
[ ] Preparation for Release 3.0.0

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#800]
This issue is created to collect all the tasks we need to do before the 3.0.0 Release (Was 2.2.0 but this release contains so much useful features and fixes that it deserves a major version).

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#836)
- [x] Update Readme.md (#836)
- [x] Tag the source code

### Pending PRs
- [x] Better structure and usage of third-party repositories #793
- [x] Using alternative PWM support as an optional feature.
- [x] SSL support, using [axTLS](http://axtls.sourceforge.net/) and [lwirax](https://github.com/attachix/lwirax), restructured so that it comes as third-party repository. HTTP, MQTT and Websocket over SSL are supported. (#596)
- [x] Better API documentation (#812 )
- [x] Better Websocket support (#806, #809)
- [x] SSL support for Websocket client (#819). 
- [x] Using the latest spiffs version (#816) 
- [x] Custom crash handler. If can be used to save crashes (stack dump, reset reason, etc) locally and send them to a remote system on the next start. Or save statistics about  alternative firmware ROMs and decide which one to use based on number of crashes, for example. (#826)
- [x] Custom Heap Allocation based on Umm-Malloc. (#835)

### SmingRTOS
- [ ] Reapplying PR #793 to SmingRTOS so that we minimize the effort and files that need to be changed/migrated.

#### State of the provided samples 

Name | Status with SDK 1.4 | Status with SDK 1.5 | Remarks | Maintainer  |
---------| ---------------------------|-----------------------------|--------------|-----------|
Accelerometer_MMA7455 | :question: | :question: | |
Arducam | :question: | :question: | |
Basic_AirUpdate | :question: | :question: | |
Basic_APA102 | :question: | :question: | |
Basic_Blink | :sunny: | :sunny: | ||
Basic_Capsense | :question: | :question: | |
Basic_Debug | :sunny: | :sunny: | | slaff
Basic_Delegates | :sunny: | :sunny: | |
Basic_HwPWM | :question: | :question: | |
Basic_Interrupts | :question: | :question: | |
Basic_Neopixel | :question: | :question: | |
Basic_ProgMem | :question: | :question: | |
Basic_PWM | :question: | :question: | |
Basic_rBoot | :sunny: | :sunny: | |raburton|
Basic_ScannerI2C | :question: | :question: | |
Basic_Serial | :sunny: | :sunny: | |
Basic_Servo | :question: | :question: | |
Basic_SmartConfig | :sunny: | :sunny: | ||
Basic_Ssl | :question: | :sunny: |  | slaff
Basic_WebSkeletonApp | :question: | :question: | |
Basic_WiFi | :question: | :question: | |
CommandProcessing_Debug | :question: | :question: | |
Compass_HMC5883L | :question: | :question: | |
DNSCaptivePortal | :sunny: | :sunny: | If you have issues check #797 |
DS3232RTC_NTP_Setter | :question: | :question: | |
Echo_Ssl | :sunny: | :sunny: |  | slaff
FtpServer_Files | :sunny: | :sunny: |  Fixed in 19d977a6a1267e7429ddd9c9eedf6266149e3b48 |
Gesture_APDS-9960 | :question: | :question: | |
HttpClient_Instapush | :question: | :question: | |
HttpClient_ThingSpeak | :question: | :question: | |
HttpServer_AJAX | :sunny: | :sunny: | |
HttpServer_Bootstrap | :sunny: | :sunny: | |
HttpServer_ConfigNetwork | :sunny: | :sunny:  | If you have issues check #797 |
HttpServer_WebSockets | :sunny: | :sunny: |  |
Humidity_DHT22 | :question: | :question: | |
Humidity_SI7021 | :question: | :question: | |
IR_lib | :question: | :question: | |
LED_WS2812 | :question: | :question: | |
Light_BH1750 | :question: | :question: | |
LiquidCrystal_44780 | :question: | :question: | |
MeteoControl | :question: | :question: | |
MeteoControl_mqtt | :question: | :question: | |
MqttClient_Hello | :sunny:  | :sunny: | SSL support is working too. Possible high latency #547 | slaff
PortExpander_MCP23017 | :question: | :question: | |
PortExpander_MCP23S17 | :question: | :question: | |
Pressure_BMP180 | :question: | :question: | |
Radio_nRF24L01 | :question: | :question: | |
Radio_RCSwitch | :question: | :question: | |
Radio_si4432 | :question: | :question: | |
ScreenLCD_5110 | :question: | :question: | |
ScreenOLED_SSD1306 | :question: | :question: | |
ScreenTFT_ILI9163C | :question: | :question: | |
ScreenTFT_ILI9340-ILI9341 | :question: | :question: | |
ScreenTFT_ST7735 | :question: | :question: | |
SDCard | :question: | :question: | |
SystemClock_NTP | :question: | :question: | |
TcpClient_NarodMon | :question: | :question: | |
Telnet_TCPServer_TCPClient | :question: | :question: | |
Temperature_DS1820 | :question: | :question: | |
UdpServer_Echo | :question: | :question: | |
UdpServer_mDNS | :question: | :question: | |
Ultrasonic_HCSR04 | :question: | :question: | |
Websocket_Client | :sunny: | :sunny: | For SSL support read the comments from #819 |avr39-ripe|

#### Resource Usage
- [ ] We should collect information about the RAM/Flash usage for this release. 

* Overall performance and issues

**Comment by slaff** [comment]
@alonewolfx2 @robotiko Can you test the Basic_Neopixel sample from the latest source code and tell me if it is working on your devices?

**Comment by harry-boe** [comment]
i still struggle with the toolchain after the OSX Sierra update.
Maybe someone can point me to some instruction on how to use the Docker container to get around the OSX issues ?

**Comment by slaff** [comment]
> how to use the Docker container

@harry-boe Read the documentation: https://github.com/SmingHub/Sming/wiki/Docker-Quickstart.

**Comment by slaff** [comment]
@anakod Can you check if the Radio_RCSwitch sample is working on a real device with the latest code? It would be great if you can help us test other samples that have unknown status in the list above.
