### ISSUE TITLE
Preparation for Release 3.0.1

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#844]
This issue is created to collect all the tasks we need to do before the 3.0.1 release.

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h
- [x] Update Readme.md
- [x] Tag the source code

### Issues that need to be addressed
- [x] The `master` branch will be our release branch. It should contain all submodules and patched sources directly applied in the source tree. The tagging of the release should be done on that branch. This will fix the issue with the release zip file (see #840 ) not containing all third-party submodules and missing the patches for them.

### Merged PRs
- [x] Better compilations with Windows UDK (#842)
- [x] Better documentation for Server and ServoChannel (#862)
- [x] Fix for samples/ScreenTFT_ILI9340-ILI9341 (#865)
- [x] Fixed compilation of Sming with custom heap based on umm_malloc (#868)
