### ISSUE TITLE
** Preparation for Release 3.1.0 **

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#870]
This issue is created to collect all the tasks we need to do before the 3.1.0 release (Was 3.0.2 but this release contains major changes that should be reflected in the version number).

Expected Date:  12th of February, 2017

### Source Code
- [x] Update the API documentation and publish the update in the `gh-pages` branch.
- [x] Update Sming/SmingCore/SmingCore.h
- [x] Update Readme.md
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### Major PRs
- [x] Custom LWIP compilation by default for 1.5 and 2.0 SDKs (#878)
- [x] Refactored `HardwareSerial` for better responsiveness and speed. Allowed the use of UART1. (#894, #923) 
- [x] rBootHttpUpdate: Hooks added for signed and/or encrypted OTA (#893). See [wiki](https://github.com/SmingHub/Sming/wiki/Signed-OTA) for details
- [x] SDK 2.0 compatibility and better Spiffs mounting logic. ( #921 )
- [x] Initial support for [YeeLight smart WiFi bulbs](http://www.yeelight.com/en_US/product/wifi-led-c). ( #925 )
- [x] AM2321 I2C sensor support ( #931 ) 

All merged PRs in this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/8?closed=1)

## Ideas
- [x] Drop "official" support for SDK 1.4 (it will still work, but we should concentrate on SDK 2.0) (#926)
- [x] Set the compilation to use custom LWIP by default. (#929)

## Docs ToDo
- [x] Add compatability matrix in Readme.md (#919)
- [x] Add more information about the custom LWIP compilation (#912).
