### ISSUE TITLE
** Preparation for Release 3.1.2 **

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#924]
This issue is created to collect all the tasks we need to do before the 3.1.2 release. (was 3.1.1 but we already have as [3.1.1 hotfix](https://github.com/SmingHub/Sming/releases/tag/3.1.1) )

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#997)
- [x] Update Readme.md (#997)
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### Merged PRs
- [x] Fix compilation of native spiffy executable (#1012)
- [x] Linker script refactoring. (#968)
- [x] Docker generation changes (#955).  Based on Alpine with Cloud9 and Xtensa GCC toolchain.
- [x] Move the rBoot linker file to the library ld directory. (#948)
- [x] Add UDK on Windows to our CI system. ( #956 )
- [x] Move debugf strings into Flash (#927)

 All merged PRs in this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/9?closed=1)

## Clean-up
- [x] Remove the text "Spiffy : Source included in Sming repository" from the Readme file (#996)
- [x] In samples/Gesture_APDS-9960 remove the log file from repo (#996)

and more.

**Comment by avr39-ripe** [comment]
From gitter.im chat
0. Change default to open-lwip and binary lwip as optional feature
1. make TCP_MSS configurable by Makefile knob
2. make ip forwarding feature configurable by Makefile knob
