### ISSUE TITLE
** Preparation for Release 3.2.0 **

### ISSUE THREAD

**Issue by slaff** [SmingHub/Sming#977]
This issue is created to collect all the tasks we need to do before the 3.2.0

### Source Code
- [x] Update Sming/SmingCore/SmingCore.h (#1107)
- [x] Update Readme.md (#1107)
- [x] Merge develop into master
- [x] Tag the source code in the master branch

### Clean-up
- Removing all code related to the Espressif bootloader and using rBoot as bootloader (#1070 )
- [x] Removed Basic_AirUpdate (#1070)
- [x] Removed HttpFirmwareUpdate ( we have rBootHttpUpdate ) (#1070)
- [x] Deprecated WifiStation::waitConnect (#1071, #1072)
- [x] Deprecated DriverPWM( aka Software PWM)

### Merged PRs
- [x] SPI mode fixes (#1083)
- [x] SSL - support to check fingerprint of public key. Useful in cases where the private key is reused for certificates over longer period of time.  (#1034)
- [x] Asynchronous AT command client ( to communicate with GSM/GPRS modules that use AT commands) (#1033)
- [x] Switched to i2c HAL and Wire libraries from the esp8266/Arduino project. (#1061)
- [x] Added NFC support (#1049)

And multiple bug fixes to the code and the documentation.

All merged PRs in this release can be seen from [here](https://github.com/SmingHub/Sming/milestone/10?closed=1)

### Moved to the next release
- [ ] Working example of simple Wifi repeater with custom LWIP and IP forwarding in LWIP. (#963)
- [ ] HttpClient should have a method `send(HttpRequest, completedCallback)` to allow custom requests with HTTP methods like PUT, DELETE, etc and custom headers.  ( Planning and initial work is [on the way](https://github.com/slaff/Sming/issues/5), will land in version 3.5 or 4.0 ... )

## Things TODO:
- [ ] Host `chocolately` as a separate repository in SmingHub.(Related to #708 )

**Comment by slaff** [comment]
@anakod Can you add for the Sming github repo a big yellow or orange label with test "Release Prep" ? This way we could distinguish easily release preps from other issues.

**Comment by anakod** [comment]
Yes, I can of course. Can you explain what is it? :)
I'm very like your idea of structuring every release, because it's make process much more transparent, so any improvements here will be helpful, I think.

**Comment by ADiea** [comment]
> Simplify FakePgmSpace: if the compiler supports mforce-l32i the functions defined here should match the standard ones. For example strlen_P should be the actual strlen. The compiler will take care to do the l32i magic.
@slaff are you sure you understand mforce-l32i completely? It forces all reads and writes to be aligned. This can be a big performance penality + code size. Also as I understand it only works for multiple of 4 bytes ex if you have 40 bytes I don't quite understand how it will read until byte 40.  So in my opinion this is a tricky compiler option, my windows compiler does not support it and I wouldn't use it anyway as far as I read about it on original post in igrr/esp-arduino

**Comment by slaff** [comment]
> Yes, I can of course. Can you explain what is it? :)

@anakod Please, read  [here](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) how to create "label". Orange color  and text "Release Prep".

**Comment by slaff** [comment]
> are you sure you understand mforce-l32i completely? It forces all reads and writes to be aligned. 

@ADiea I guess not :). But I can easily check this. I guess I will have time on Monday to do this. Thanks for bringing that up.

**Comment by ADiea** [comment]
Guys just so you know I will be in vacation following next 2 wks, will be unable to fix anything else from the list for the current release :)
